# Generated by Django 2.2 on 2022-03-17 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='comment',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='package',
            name='current_version',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='package',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='package',
            name='public',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='package',
            name='tags',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='version',
            name='dependencies',
            field=models.TextField(default=''),
        ),
    ]
