# Generated by Django 2.2 on 2022-03-17 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20220317_0156'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readme', models.BooleanField(default=False)),
                ('code_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='version',
            name='code',
        ),
        migrations.AlterField(
            model_name='version',
            name='version_ID',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='version',
            name='code_files',
            field=models.ManyToManyField(to='manager.File'),
        ),
    ]
