# Generated by Django 2.2.26 on 2022-03-24 13:08

from django.db import migrations, models
import manager.models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20220324_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='current_version',
            field=models.TextField(default='0.0.0'),
        ),
        migrations.AlterField(
            model_name='package',
            name='readme',
            field=models.FileField(blank=True, upload_to=manager.models.Package.getUploadDir),
        ),
    ]
