# Generated by Django 2.2.26 on 2022-03-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20220324_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='current_version',
            field=models.CharField(default='0.0.0', max_length=20),
        ),
        migrations.AlterField(
            model_name='version',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='version',
            name='dependencies',
            field=models.TextField(blank=True, default=''),
        ),
    ]
